mqtt:
  uri: mqtt://localhost
  prefix: pushover
service:
  targets:
    # Will allow sending on pushover/send/myapp/text and pushover/send/myapp/message
    - key: myapp
      token: ""
      user: ""
      title: "My App"
